project:
  type: book
  output-dir: docs
book:
  title: HSMA - the little book of DES
  subtitle: An introduction to writing discrete event simulation models for healthcare (and beyond) in SimPy
  author: Dan Chalk and Sammi Rosser
  date: 26/03/2024
  chapters:
  - index.qmd
  - part: "Part 1 - DES Concepts and Design"
    chapters:
    - intro_to_des_concepts.qmd
    - exercise_des_design.qmd
  - part: "Part 2 - Your First SimPy Model"
    chapters:
    - intro_to_simpy.qmd
    - recommended_structure_classes_for_des_models.qmd
    - an_example_simpy_model.qmd
    - an_example_simpy_model_multiple_steps.qmd
    - an_example_simpy_model_branching.qmd
    - exercise_gp.qmd
  - part: "Part 3 - Extending Your Model"
    chapters:
    - model_warm_up.qmd
    - priority_based_queueing.qmd
    - modelling_resource_unavailability.qmd
    - choosing_distributions.qmd
    - reproducibility.qmd
    - reneging_balking_jockeying.qmd
    - modelling_variable_arrival_rates.qmd
    - exercise_des_advanced.qmd
  - part: "Part 4 - Advanced Performance Tracking and Visualisation"
    chapters:
    - tracking_resource_utilisation.qmd
    - other_model_metrics.qmd
    - visualising_model_metrics.qmd
    - visualising_des_models.qmd
  - part: "Part 5 - Advanced Concepts"
    chapters:
    - requesting_multiple_resources.qmd
    - scheduling_arrivals.qmd
    - appointment_style_booking_models.qmd
    - appointment_style_booking_models_advanced.qmd
    - appointment_style_booking_models_multistep.qmd
    - testing_large_numbers_scenarios.qmd
    - running_parallel_cpus.qmd
    - intro_creating_web_apps.qmd
  - alternative_foss_simulation_libraries_software.qmd
  - further_reading.qmd
  - references.qmd
  cover-image: resources/logos/hsma_logo_transparent_background_large.png
  favicon: resources/logos/hsma_logo_transparent_background_large.png
  search: true
  page-navigation: true
  back-to-top-navigation: true
  navbar:
    search: false
    background: '#8A1E1E'
  sidebar:
    search: true
    style: docked
    logo: resources/logos/hsma_logo_transparent_background_large.png
    background: '#111111'
  open-graph: true
  # cookie-consent:
  #   type: express
  #   style: headline
  #   palette: dark
bibliography: references.bib
format:
  html:
    highlight-style: github
    css: include/webex.css
    include-after-body: include/webex.js
    theme:
      dark:
      - darkly
      - theme-dark.scss
      - resources/fonts/css/lexend.css
      light:
      - flatly
      - theme-light.scss
      - resources/fonts/css/lexend.css
    grid:
      sidebar-width: 250px
  pdf:
    output-file: hsma_des_book
    toc: true
    highlight-style: github
    number-sections: true
    colorlinks: true
    toc-depth: 2
