project:
  type: book
  output-dir: docs
book:
  title: HSMA - the little book of DES
  google-analytics:
    tracking-id: "G-3YZDF78XLF"
    anonymize-ip: true
  cookie-consent:
    type: express
    style: simple
    palette: dark
  subtitle: An introduction to writing discrete event simulation models for healthcare (and beyond) in SimPy
  author: Dan Chalk, Sammi Rosser and Amy Heather
  date: 2024/02/26
  chapters:
  - index.qmd
  - part: "Part 1 - DES Concepts and Design"
    chapters:
    - intro_to_des_concepts.qmd
    - exercise_des_design.qmd
  - part: "Part 2 - Your First SimPy Model"
    chapters:
    - intro_to_simpy.qmd
    - recommended_structure_classes_for_des_models.qmd
    - an_example_simpy_model.qmd
    - an_example_simpy_model_multiple_steps.qmd
    - an_example_simpy_model_branching.qmd
    - exercise_gp.qmd
  - part: "Part 3 - Extending Your Basic Model"
    chapters:
    - model_warm_up.qmd
    - priority_based_queueing.qmd
    - modelling_resource_unavailability.qmd
    - choosing_distributions.qmd
    - getting_the_distribution_from_real_world_data.qmd
    - reproducibility.qmd
    - reneging_balking_jockeying.qmd
    - one_or_the_other.qmd
    - modelling_variable_arrival_rates.qmd
    - requesting_multiple_resources.qmd
    - exercise_des_advanced.qmd
  - part: "Part 4 - Growing your Confidence as a Modeller"
    chapters:
    - part_4_intro.qmd
    - multiple_entity_types.qmd
    - example_multiple_entity_types_similar_pathways.qmd
    - scheduling_arrivals.qmd
    - appointment_style_booking_models.qmd
    - appointment_style_booking_models_advanced.qmd
    - appointment_style_booking_models_multistep.qmd
    - example_models.qmd
  - part: "Part 5 - Debugging, Model Validation and Visualising Results"
    chapters:
    - basic_debugging_tactics.qmd
    - tests.qmd
    - event_logging.qmd
    - process_logs_with_bupar.qmd
    - visualising_des_models.qmd
    - tracking_resource_utilisation.qmd
    - other_model_metrics.qmd
    - visualising_model_metrics.qmd
  - part: "Part 6 - Model Interfaces and Outputs"
    chapters:
    - intro_creating_web_apps.qmd
  - part: "Part 7 - Model Reporting and Sharing"
    chapters:
    - stress_des.qmd
    - stars.qmd
    - sharing_reproducible_models.qmd
  - part: "Part 8 - Advanced Concepts"
    chapters:
    - testing_large_numbers_scenarios.qmd
    - running_parallel_cpus.qmd
  - alternative_foss_simulation_libraries_software.qmd
  - further_reading.qmd
  - references.qmd
  cover-image: resources/logos/cover_image_bing_image_generator.jpeg
  favicon: resources/logos/hsma_logo_transparent_background_large.png
  search:
    location: navbar
    type: overlay
  page-navigation: true
  back-to-top-navigation: true
  navbar:
    background: '#8A1E1E'
    right:
      - icon: github
        href: https://github.com/hsma-programme/hsma6_des_book
        aria-label: GitHub
  sidebar:
    search: true
    style: docked
    logo: resources/logos/hsma_logo_transparent_background_large.png
    background: '#111111'
  open-graph: true
  # cookie-consent:
  #   type: express
  #   style: headline
  #   palette: dark
bibliography: references.bib
format:
  html:
    execute:
      freeze: auto
    highlight-style: github
    css: include/webex.css
    include-after-body: include/webex.js
    theme:
      dark:
      - darkly
      - theme-dark.scss
      - resources/fonts/css/lexend.css
      light:
      - flatly
      - theme-light.scss
      - resources/fonts/css/lexend.css
    grid:
      sidebar-width: 300px
      body-width: 900px
      margin-width: 300px
      gutter-width: 1.5rem
  # pdf:
  #   output-file: hsma_des_book
  #   toc: true
  #   highlight-style: github
  #   number-sections: true
  #   colorlinks: true
  #   toc-depth: 2
