# Model Readiness Checklist

Judging whether a model is ready to support real-world decisions is often a subjective choice. The checklist below offers practical guidance to **help you decide when your model is ready enough to be used**.

We recognise that models are **often developed in less-than-ideal contexts**, where there isn't enough time or resource to implement all the automated tests you might like. This checklist therefore aims to give you a meaningful minimum to aim for, giving you the best possible chance of delivering an output that is valid for use in decision-making.

The checklist is divided into three levels:

* **Bronze**: For models used in small- to medium-scale decision-making within a single organisation. Focuses on harm reduction and catching critical errors using largely manual or visual checks.

* **Silver**: For models that inform larger or costlier decisions, or are applied across multiple areas. Encourages stronger assurance measures (e.g. peer review, partial automation) where feasible.

* **Gold**: For models that will be reused, adapted, or published (e.g. in scientific journals), where the original author may not be involved. Emphasises transparency, documentation, and robustness to long-term or external use.


## Bronze

### Visualisations

Visualise the following:

- [ ] Arrivals over time (using a dotplot or heatmap)
- [ ] Resource use over time (overall as a line plot, plus recurrently at relevant timescale if recurrent patterns of resource use at )
- [ ] Distributions of generated activity times
- [ ] Distributions of generated inter-arrival times
- [ ] Queue lengths over time

### Core Logic Checks

- [ ] Watch the journey of several individuals (via logs or animations)
- [ ] Check that all described stages demonstrate at least some activity during a sufficiently long, representative run
- [ ] Implement a random seed implemented for reproducibility under same inputs
    - [ ] Verify this visually by running twice with the same seed, confirming outputs do not change
- [ ] Manually check that the number of entities in = the number of entities out + those still in model (no 'lost' entities in queues with no sink)
- [ ] Manually check that entities are never in two places at once
- [ ] Manually check that resources are never simultaneously in use by two entities at once (or whatever variation is appropriate for your model)
- [ ] Outputs are being derived from a minimum of 30 runs (ideally more)
- [ ] Warm up length visually checked to be appropriate
- [ ] Manually review that time units have been used consistently throughout the code (e.g. time inputs don't swap from minutes to hours at any point)
- [ ] Manually check logs to ensure that resources are not used at times where they should be obstructed/unavailable (e.g. during breaks, evenings, weekends)

### Key checks against the real system

- [ ] Number of entities arriving in sim verified against historical patterns (averages sensible, distributions sensible)
    - [ ] If relevant, this is also checked for entity subtypes/entities with different attributes where it is important that these patterns match the real system
- [ ] Generated activity times visually verified (averages sensible, distribution sensible)
    - [ ] If relevant, this is also checked for entity subtypes/entities with different attributes where it is important that these patterns match the real system
- [ ] Visual check that there are no implausible activity lengths, with a cap applied if necessary to resolve this
- [ ] Visual check that there are no implausible inter-arrival times for entities, with a cap applied if necessary to resolve this
- [ ] Visual check of KPI outputs against the historical baseline - do these look sensible and similar to historical data?

### Process and Stakeholder Checks

- [ ] Approve the simulation process map with stakeholders
- [ ] Check the scenario outputs with stakeholders - do they feel reasonable?
    - Note that stakeholder responses to outputs shouldn't necessarily be taken as a definite right/wrong judgment on the model - but they may help to sense check or indicate areas for more attention

### Documentation

- [ ] Write a readme that
    - [ ] Explains how to run the model
    - [ ] Gives a brief overview of the system being modelled
- [ ] Include sufficient comments in your work to help people understand non-obvious elements of the code

## Silver

### Model Robustness

- [ ] Undertake sensitivity analysis

### Documentation

- [ ] Add docstrings
- [ ] Complete a formal model reporting checklist (e.g STRESS-DES)

### Code Review

- [ ] Have a code review undertaken by someone else (see [the DES RAP book: peer review](https://pythonhealthdatascience.github.io/des_rap_book/pages/guide/sharing/peer_review.html))

### Automated Testing

- [ ] Define formal automated tests:
    - [ ] Model running successfully
    - [ ] Varying results are obtained when using different seeds and the same parameters
    - [ ] Identical results are obtained when the same seed and parameters are used
    - [ ] Number of entities in = the number of entities out + those still in model (no 'lost' entities in queues with no sink)
    - [ ] Utilisation never exceeds capacity (i.e. resources are never in use by multiple entities, unless allowed in your model)
    - [ ] All stages of the model show some activity (i.e. there are no 'orphaned' steps)
    - [ ] Simple 'expected behaviour' when parameters are varied
        - [ ] longer activity time = worse performance
        - [ ] more arrivals = longer queues
    - [ ] Write tests for behaviour under extreme conditions
        - [ ] Heavy Demand
        - [ ] Little to no demand

### Reproducibility

- [ ] Meet the core requirements of the STARS reproducibility framework


## Gold

### Documentation

- [ ] Documentation site created

### Reproducibility

- [ ] Complete some or all of the optional elements of the STARS framework

### Model Efficiency

- [ ] Parallelisation implemented

### Model Communication and Validation

- [ ] Animated model output created (if appropriate)
    - Animations also have a role to play in model validation - inspecting the animation, including with non-technical stakeholders, can help identify subtle bugs

### Best Practice around Variability and Model Setup

- [ ] Formal method used for determining warm-up period
- [ ] Formal method used for determining appropriate replication count

### Automated Testing

- [ ] Define formal automated tests for:
    - [ ] Comparison of base case outputs to historical data for key metrics
    - [ ] Statistical testing of generated distributions against real-world data (e.g. Kolgomorov-Smirnov Test)
